### PR TITLE
RDP RHS info: remove onclick events and keep regular a elements

### PR DESCRIPTION
**Pull request by trilopin**
#### Summary
Remove onclick handlers in the items that are pure links in RHS overview at Run Details Page.
That make the cmd+click works natively due to the inner `<a>`. We lose the click handler for the whole row, but it's not critical since the links at the right part catch naturally all the clicks.

Done for playbook and channel links.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-45960

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

### CODE REVIEW

**Review by gbochora — APPROVED** [review]

**Review by lieut-data — APPROVED** [review]
Nice! One possible suggestion: would it make sense to have `ItemLink` itself be an `Item` (vs. being contained within one), preserving the "whole row" clickability? 

Right now, the `Participants` row will still be fully clickable, but it might be odd to have more rows that highlight on hover but are only clickable in small places?

**Comment by trilopin** [comment]
> Nice! One possible suggestion: would it make sense to have `ItemLink` itself be an `Item` (vs. being contained within one), preserving the "whole row" clickability?
> 
> Right now, the `Participants` row will still be fully clickable, but it might be odd to have more rows that highlight on hover but are only clickable in small places?

I tried this first. I made the row clickable with <a> and some ugly hacks to remove <a> formatting (text decoration, focus, color, etc..). In the end, it seemed more natural to just use links in the links.

That said, it's true that we have 3 different interactions in a very short space:
- channel and playbook -> pure link on the right
- participants -> whole row clickable and navigate to other RHS
- followers -> button clickable (not the row, or even the right part)

cc @abhijit-singh to get some insights

**Review by abhijit-singh — APPROVED** [review]
The clickable area is different for different rows but that's okay in my opinion because it is different kinds of objects. The downside of making the entire row clickable in case of `playbook` and `channel` is that accidental clicks can happen a lot more and it takes you to a completely different page/product. 

Listing a couple of random things I noticed around `run info` but might not be related to this PR at all so feel free to go ahead and merge this and I can create separate tickets for these. 
1. Noticed there's no arrow at the end of the `Participants` row which was there in the designs. 
image
2. The `1 participant` label is misaligned. It should be left aligned with the user avatars.
image

**Comment by lieut-data** [comment]
Thanks, @abhijit-singh! Filed https://mattermost.atlassian.net/browse/MM-46256 and https://mattermost.atlassian.net/browse/MM-46257 to track these two observations and queued them up for this sprint.

**Pull request merged**
