### PR TITLE
MM-41513: Restrict private playbooks

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary

This PR brings back the restriction on private playbooks:
- It reverts https://github.com/mattermost/mattermost-plugin-playbooks/pull/999
- If the server does not have an Enterprise license:
  - It disables the private option in the playbook creation modal, adding the green key icon (first screenshot)
  - It hides the `Convert to private playbook` button in the `Manage access` modal (second screenshot: that button is usually right after the `Everyone in eligendi can view this playbook`)
  - It restricts the conversion in the API level

image
image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41513

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [X] Unit tests updated

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Thank you, @agarciamontoro!

**Review by crspeller — APPROVED** [review]
Sorry for the delay. I thought I approved this yesterday 🤦

**Comment by agarciamontoro** [comment]
No problem, and thanks!

**Review by abhijit-singh — COMMENTED** [review]
Looks good @agarciamontoro! Just one change request — in the create modal, can we trigger the tooltip while hovering anywhere over the `private playbook` button instead of just the key icon? Sorry, this should've been clearer in the designs.

**Comment by agarciamontoro** [comment]
> can we trigger the tooltip while hovering anywhere over the private playbook button instead of just the key icon? Sorry, this should've been clearer in the designs.

Sure! Do we want the tooltip to still show on top of the green key icon, or on top of the whole button?

**Comment by agarciamontoro** [comment]
@abhijit-singh, this is what I means with "on top of the whole button", which is the easiest solution:
image

**Comment by agarciamontoro** [comment]
Push the changes with the tooltip on top of the whole button. Let me know what you think, @abhijit-singh :)

**Review by abhijit-singh — APPROVED** [review]
Yes that's perfect, thank you @agarciamontoro! 🚀

**Pull request merged**
