### PR TITLE
MM-38188 Adding missing primary keys

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Adds missing primary keys to IR_PlaybookMember, IR_StatusPosts, IR_TimelineEvent, IR_ViewedChannel
Esentally does:
```sql
ALTER TABLE IR_PlaybookMember ADD PRIMARY KEY (MemberID, PlaybookID);
ALTER TABLE IR_StatusPosts ADD PRIMARY KEY (IncidentID, PostID);
ALTER TABLE IR_TimelineEvent ADD PRIMARY KEY (ID);
ALTER TABLE IR_ViewedChannel ADD PRIMARY KEY (ChannelID, UserID);
```
with more steps.

Added a test so we don't make this mistake again.

#### Ticket Link
http://mattermost.atlassian.net/browse/MM-38188

#### Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
- [x] Unit tests updated

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
thank you – – especially for the unit test!￼

**Review by agarciamontoro — COMMENTED** [review]
Really cool!

I have a question: why are we modifying the original creation of the tables, and not simply adding the migration? I'm concerned that this somehow fake our tests on the migrations, as they are effectively exercising a different scenario than what the real databases have. For example, we're not testing the `ALTER TABLE` statements from the `addPrimaryKey`, if I understood the code correctly.

The new test is great, by the way :)

**Comment by agarciamontoro** [comment]
@crspeller 

>  I mostly did it because I don't like leaving incorrect code around for people to copy paste mistakenly.

That's a good argument, but the table creation code is still incorrect, as we modify the tables in every migration. If we change the original code of the table creation, now we have a mix of correct and incorrect code, and I'd say that's worse than having an incorrect original code that is fixed through all the migrations.

In general, I understand the database schema as the application of every migration in the file, so it is always correct (as far as we know, of course, every new bug is fixed through a new migration).

I'm 3/5 about keeping the original code. Another solution would be to just squash all migrations and write an actual correct schema creation.

Thoughts?

**Comment by crspeller** [comment]
@agarciamontoro Reverted the changes to the original table creations.

**Review by agarciamontoro — APPROVED** [review]
Cool, thanks for this!

**Pull request merged**
