### PR TITLE
Exclude err shadowing

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary

This is a proposal to exclude variable shadowing from the linter, but only with `err` variables. This error has not helped me a single time, only annoyed me. 

I added the exclude rule and a sample of what it lets us do (avoid `err2`, basically). I stole the idea from https://github.com/golangci/golangci-lint/issues/166#issuecomment-617517087.

What do you think?

#### Ticket Link
--

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

### CODE REVIEW

**Review by crspeller — APPROVED** [review]
Yes this is always causing me to do err2 err3 which is hideous.

**Comment by cpoile** [comment]
Yes / no on this? I'm fine either way I guess. 🤷

**Review by cpoile — APPROVED** [review]

**Review by iomodo — APPROVED** [review]

**Comment by lieut-data** [comment]
I'm willing to give it a go :)

**Review by calebroseland — APPROVED** [review]

**Comment by agarciamontoro** [comment]
Merging this now, as it does not affect the code at all (I had to remove the sample I did when merging master here). The failing E2E test is not caused by this (it's failing everywhere).

**Pull request merged**
