### PR TITLE
MM-41054 Add tour points for playbook preview.

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Tour points for playbook preview. No autostart (to be hooked up with `const startTutorial = true`). 

Screenshots:
image
image
image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41054

### CODE REVIEW

**Review by iomodo — APPROVED** [review]
Looks great @crspeller!

**Review by calebroseland — APPROVED** [review]
LGTM!

**Review by abhijit-singh — APPROVED** [review]
Looks good 👍 
A couple of minor non-blocking nits —
- In the second tour point, can we highlight the `In this playbook` heading as well?
image
- Any chance we could get rounded corners for the highlighted areas? 🙈 
image

**Comment by crspeller** [comment]
@abhijit-singh Expanded to cover the title:
image

As for the rounded corners that style comes from the webapp component. We could modify our component (with some difficulty) to have rounded corners there, but they would look different then the other places. We can do this on a seperate PR if that's what we want to do.

**Pull request merged**
