### PR TITLE
Gh 1524 timeline events participants

### PR DESCRIPTION
**Pull request by trilopin**
## Summary
Timeline events for add/remove participants.
Service functions `AddParticipants`and `RemoveParticipants` have change to trigger timeline events:
- we keep already existent event type user_joinedleft if it's participate/leave run flow
- we use participanmts_changed new timeline event when we add/remove users 

RHS Timeline item has been refactored to handle more complex literals. summary/summarytitle for user_joinedleft moved from server to webapp (to be translatable and consistent).

**Added several**
Screenshot 2022-10-27 at 13 07 02

**added one**
Screenshot 2022-10-27 at 13 06 56

**remnoved one**
Screenshot 2022-10-27 at 13 06 12

**participate & leave**
Screenshot 2022-10-27 at 16 27 35

## Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1524

## Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] Unit tests updated

### CODE REVIEW

**Review by gbochora — APPROVED** [review]
Nice! 🎉 I left just a few non-blocking comments.

**Comment by trilopin** [comment]
> Nice! 🎉 I left just a few non-blocking comments.

I forgot to push the last commit which cover some of your points. Will check the rest of them

**Review by crspeller — APPROVED** [review]
Nice!

**Review by abhijit-singh — CHANGES_REQUESTED** [review]
Looks good visually but I think I spotted a bug. Whenever I add someone to a run, the timeline event shows as `I` joined the run. 

https://user-images.githubusercontent.com/14369607/199454139-a65c5ca2-c444-40a8-b05d-10c030c5f377.mov

**Comment by trilopin** [comment]
> Looks good visually but I think I spotted a bug. Whenever I add someone to a run, the timeline event shows as `I` joined the run.
> 
>  bScreen.Recording.2022-11-02.at.2.47.37.PM.mov

You're right. I introduced an important error when I merged the simplification. Last minute change :(.

It's fixed now

**Review by abhijit-singh — APPROVED** [review]
💯

**Pull request merged**
