### PR TITLE
[MM-61124] Add diagnostics data to the Support Packet

### PR DESCRIPTION
**Pull request by hanzei**
## Summary
When a Support Packet gets generated, the plugin now includes diagnostics data via a `diagnostics.yaml` file into the Packet.

Example content of `playbooks/diagnostics.yaml`:

```yaml
version: 2.0.1+74aea618
total_playbooks: 1
active_playbooks: 1
total_playbook_runs: 2
```

Requires https://github.com/mattermost/mattermost/pull/28833 on the server side. https://github.com/mattermost/mattermost-plugin-playbooks/pull/1956 needs to be merged first.

See https://mattermost.atlassian.net/wiki/spaces/CLOUD/pages/3083108354/Diagnostics+data+from+Core+Plugins+to+the+Support+Packet for more context.

## Ticket Link
https://mattermost.atlassian.net/browse/MM-61124

## Checklist

- [x] ~~Telemetry updated~~
- [x] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
Neat! Code looks good to me :)

**Comment by hanzei** [comment]
@wiggin77 Gentle reminder to review the PR

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by hanzei** [comment]
Per discussion with @raghavaggarwal2308, QA testing will happen post merge.

**Pull request merged**
