### PR TITLE
MM-40503/MM-40270: Fix formatted message page crash

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Fix crash on playbook usage page when you are the system admin on and E10 or unlicenced server. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40503
https://mattermost.atlassian.net/browse/MM-40270

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
i18n magic!

**Review by calebroseland — APPROVED** [review]
Thanks for fixing! I hadn't gotten around to https://mattermost.atlassian.net/browse/MM-40270 before heading out.

**Comment by lieut-data** [comment]
Ooh, I /thought/ I had seen this one before! I guess this resolves https://mattermost.atlassian.net/browse/MM-40270 too?

**Comment by crspeller** [comment]
@lieut-data Yup, that's the same issue.

**Comment by lieut-data** [comment]
Cherry picked to release-1.22.

**Pull request merged**
