### PR TITLE
MM-40881 Confirmation dialogs are removed when cancelling/restoring a task

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
Confirmation dialogs are removed when cancelling/restoring a task

**Before**

https://user-images.githubusercontent.com/37421564/152660490-e3872dd5-8620-4c9d-ae66-abcc38c92037.mov

**After**

https://user-images.githubusercontent.com/37421564/152660493-d2a33e27-d2a7-4f80-9e92-80d3de885f2c.mov

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost-server/issues/19296

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

### CODE REVIEW

**Review by gbochora — APPROVED** [review]
This is great, @sinansonmez , thank you! 🎉

**Review by abhijit-singh — APPROVED** [review]
Looks great, thanks @sinansonmez!

**Comment by sinansonmez** [comment]
Hey @cpoile could you please review this when you have time

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
