### PR TITLE
Add participant modal footer alignment fix

### PR DESCRIPTION
**Pull request by Aryakoste**
## Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27537
Jira https://mattermost.atlassian.net/browse/MM-58182

Before Screenshot:- 
playbooksModalBeforeSS

After Screenshot:-
playbooksModalAfterSS

## Checklist

~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
~~- [ ] Unit tests updated~~

### CODE REVIEW

**Comment by Aryakoste** [comment]
This type of alignment issue is also occuring in other modals. Because the modal-footer is flex and the first element is :before content. I can make the change in generic modal if needed.

footer alignment

**Comment by Aryakoste** [comment]
First the width 100% was not working i think it was not compiled properly now its working so changed to that.

**Review by crspeller — APPROVED** [review]

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @Aryakoste!

**Review by lindy65 — APPROVED** [review]
Thanks @Aryakoste 🙌 

cc @crspeller - this will need to be tested post merge once a new version of playbooks is cut

**Pull request merged**
