### PR TITLE
MM-54364: Prevent garbage telemetry for invalid run ids

### PR DESCRIPTION
**Pull request by calebroseland**
## Summary
Handle invalid `runId`s in `makeRHSOpener`

## Ticket Link
- https://mattermost.atlassian.net/browse/MM-54364

#### Checklist

Item | Y / N / NA [^1]
---|---
Telemetry updated? | Y
Gated by experimental feature flag? | N
Unit/E2E tests updated? | Y

[^1]: Yes / No / Not Applicable.

### CODE REVIEW

**Review by esarafianou — APPROVED** [review]
LGTM!

**Review by lieut-data — APPROVED** [review]

**Review by sbishel — APPROVED** [review]

**Comment by lieut-data** [comment]
@calebroseland, if there's a chance we can merge https://github.com/mattermost/mattermost-plugin-playbooks/pull/1872, it would be awesome to include it alongside your changes and whatever the next patch is.

**Comment by calebroseland** [comment]
> @calebroseland, if there's a chance we can merge #1872, it would be awesome to include it alongside your changes and whatever the next patch is.

Thanks for fixing all the E2E, @lieut-data! I'm not sure of which branch protections are preventing this from being merged, but I can't do that for some reason—would you mind merging this, as well?

**Comment by lieut-data** [comment]
@toninis, has something changed in our repo restrictions? Caleb and I both see:
CleanShot 2023-10-04 at 17 01 15@2x

I'm going to force it as a repo admin, but wondering something else has changed upstream?

**Pull request merged**
