### PR TITLE
RHS header styling fixed

### PR DESCRIPTION
**Pull request by Aryakoste**
## Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28365
Jira https://mattermost.atlassian.net/browse/MM-54343

##Screenshots
Before:- 
Before RHS Stylinh

After:- 
After RHS Styling

## Checklist

~- [ ] Telemetry updated~
~- [ ] Gated by experimental feature flag~
~- [ ] Unit tests updated~

### CODE REVIEW

**Comment by Aryakoste** [comment]
I could add the font-family to TitleContainer too which could work the same will act as global style for RHS Title Container because RHSTitleText has been given font-family of Metropolis but it would be similar i think.

**Review by crspeller — APPROVED** [review]

**Review by lieut-data — APPROVED** [review]
Thanks, @Aryakoste!

**Comment by lindalumitchell** [comment]
I set up a test server before I realized this is a plugin PR. :) Is there an artifact automatically created that I can grab and install for a quick test? I didn't see one in the usual places I thought I'd find one (but I might be a bit rusty on testing plugin PRs).

**Review by lindalumitchell — APPROVED** [review]
I'm deferring QA on this one; we can test the plugin after merge.

**Pull request merged**
