### PR TITLE
MM-38908: When clicking Run, navigate to the new URL provided by webapp

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
Use the new URL provided by webapp. See [the PR](https://github.com/mattermost/mattermost-webapp/pull/9012) there for more information.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38908

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Probably just a formality, but should we bump our `min_server_version` as part of this?

**Comment by agarciamontoro** [comment]
> Probably just a formality, but should we bump our min_server_version as part of this?

Absolutely, thanks for catching!

**Review by calebroseland — APPROVED** [review]

**Comment by lieut-data** [comment]
E2E tests appear to be failing "by design", given the dependence on the corresponding webapp change. :tada:

**Comment by agarciamontoro** [comment]
Re-running, at least master should pass now.

**Comment by agarciamontoro** [comment]
Master is passing :tada: We can wait to merge this until Monday, when `master` will be merged into `cloud`, to make sure that all E2E tests pass.

**Comment by agarciamontoro** [comment]
Re-triggering CI as soon as https://github.com/mattermost/mattermost-webapp/pull/9016 is merged.

**Comment by lieut-data** [comment]
@agarciamontoro, after merging, can you cherry-pick into a `release-1.20` branch so we can cut a `1.20.1`?

**Pull request merged**
