### PR TITLE
[GH-19313] Update snooze options text to be "for" duration

### PR DESCRIPTION
**Pull request by ryoarmanda**
#### Summary

Updates the snooze options texts to be `for <duration>` instead of `in <duration>`.

Some fixes are literal, but for a couple others, I had to break away from the imported `optionFromSeconds` function as it  formats the text to be `in <duration>`. I defined a local function that is similar to it, but formats to `for <duration>`.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/19313
(Also JIRA: https://mattermost.atlassian.net/browse/MM-40950)

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

### CODE REVIEW

**Comment by lieut-data** [comment]
@Phrynobatrachus, can you help test this PR?

**Comment by Phrynobatrachus** [comment]
Text looks updated as expected and functionality still good. :+1: 

Thanks for the PR!

**Review by Phrynobatrachus — APPROVED** [review]

**Review by gbochora — APPROVED** [review]
Nice! Thanks, @ryoarmanda!

**Pull request merged**
