### PR TITLE
[MM-39652] Fix missing suggestion when CRT is on

### PR DESCRIPTION
**Pull request by iomodo**
#### Summary
This PR fixes missing run suggestions when CRT is on

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-39652

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- [X] Unit tests updated

### CODE REVIEW

**Comment by itao** [comment]
I suggest getting buy-in from the channels team on the proposed solution for fixing ephemeral messages in threads and we spend the mana to implement it. Presumably this issue contributes to the delay in general availability of collapsed reply thread so it'd be helpful for everyone.

**Comment by iomodo** [comment]
I had a stupid bug. Please review the PR again @crspeller @agarciamontoro , it is working now.

**Review by crspeller — APPROVED** [review]
That works :)

**Review by agarciamontoro — APPROVED** [review]
Ooooh, I see. It makes sense.

**Pull request merged**
