### PR TITLE
RHS runs sort list visual improvements.

### LINKED ISSUE #1603: RHS runs list sort visual improvments
https://www.figma.com/file/eq9Nwyot47KZ9gb4pf5C2L/%E2%96%B6%EF%B8%8F-Multiple-runs-in-a-channel?node-id=807%3A234822&t=Maojsm2eha9PbGNo-4

RHS sorting needs:
- Blue check-marks
- Title "SORT RUNS BY"

### PR DESCRIPTION
**Pull request by crspeller**
## Summary
Visual improvments to runs list sorting.
image

## Ticket Link

Fixes #1603

### CODE REVIEW

**Review by m-ripper — APPROVED** [review]
Looks good!

**Review by trilopin — APPROVED** [review]
Cool 🎉

**Review by gbochora — APPROVED** [review]
Nice!

**Review by abhijit-singh — APPROVED** [review]
Looks good!

**Pull request merged**
