### PR TITLE
[GH-17956] migrate status_filter to styled component

### PR DESCRIPTION
**Pull request by maliur**
#### Summary
This will migrate webapp/src/components/backstage/playbook_runs/playbook_run_list/status_filter.scss to styled-components

This also touches these components since they shared some styling from status_filter.scss:
webapp/src/components/backstage/playbook_runs/playbook_run_list/playbook_run_list.tsx
webapp/src/components/backstage/playbooks/playbook_run_list/playbook_run_list.tsx
webapp/src/components/checklist_item.tsx
webapp/src/components/profile/profile_selector.tsx
webapp/src/components/team/create_playbook_team_selector.tsx
webapp/src/components/team/team_selector.tsx

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost-server/issues/17956

#### Checklist
~~- [ ] Telemetry updated~~
~~- [ ] Gated by experimental feature flag~~
~~- [ ] Unit tests updated~~

### CODE REVIEW

**Comment by crspeller** [comment]
@maliur Thanks for the PR! I noticed you opened as a draft. Should we wait for some more changes or would you like a review now?

**Comment by maliur** [comment]
Forgot to open it but it should be open for review now :)

**Review by crspeller — APPROVED** [review]
Looks good! Did a quick run though and didn't see any visual issues. Thanks @maliur 👍

**Review by cpoile — APPROVED** [review]
Looks great, thank you @maliur for the contribution!

**Pull request merged**
