### PR TITLE
add give feedback to run rhs list

### PR DESCRIPTION
**Pull request by trilopin**
## Summary
CleanShot 2022-12-08 at 17 01 01

Add give feedback button to Channels RHS run list.

it's not positioned fixed, it appears at the end of the list.

## Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1600

## Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [X] Unit tests updated

### CODE REVIEW

**Review by m-ripper — APPROVED** [review]
Looks good! The only thing that could potentially be improved in my opinion, is the hover color of the button. It could be the same color as the feedback button in the playbook run view and the details in the Channels RHS.

**Review by gbochora — COMMENTED** [review]
Cool! 
Two comments:
- Should we show the `Give feedback` on the black list view when there are no `in-progress/finished` runs?
- We show the `Give feedback` button on the run details view. Was it intentional? Because I couldn't find it in the designs.

**Comment by trilopin** [comment]
> We show the Give feedback button on the run details view. Was it intentional? Because I couldn't find it in the designs.

It was already there (with some subtle differences like being 14px). @abhijit-singh any change you may want to do on this matter?

> One request — Can we make the Give feedback button stick to the bottom when there aren't many runs? It can behave as it is now when the list of runs scrolls off the screen.

Pushed changes to make it fixed (also spaced differently the zero cases that were top-aligned)
CleanShot 2022-12-13 at 11 09 14

**Comment by trilopin** [comment]
Pushed changes:
- if there're enough runs feedback button will be after the last run and will be scrollable
- if there are lesser runs than visible space, the feedback button will be at bottom

additionally, I centered vertically the content for zero cases 

https://user-images.githubusercontent.com/4096774/207417472-5194a79b-d971-490d-8e89-fc7a222b77e9.mp4

**Review by abhijit-singh — APPROVED** [review]
💯 

Thank you @trilopin!

**Pull request merged**
