### PR TITLE
Updated Cypress test infrastructure (from webapp)

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
This PR imports the `cypress/support` files (and some configuration) from mattermost-webapp. It moves some of our versions of the same APIs into a "legacy" file (with methods prefixed by `legacy*`). I also intend to upstream a handful of improvements we've made.

The plan is to get this merged and then incrementally convert our e2e tests over to using purely dynamic data (i.e. new teams /users each run). In the future, I'd love to see the Cypress support library exposed as an NPM package that we could consume directly vs. copying. Note too that I opted to "copy everything" vs. just the stuff we need, to make it easier to "upgrade" our version in the future.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31698

#### Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [x] Unit tests updated

### CODE REVIEW

**Comment by agarciamontoro** [comment]
Cool :tada: Although this is a loooong PR! @lieut-data, anything we should focus on as reviewers?

**Comment by lieut-data** [comment]
@agarciamontoro, maybe just glance through the integration tests, but honestly the real meat will come in the next PR.

**Review by saturninoabril — APPROVED** [review]
>  ... intend to upstream a handful of improvements
Looking forward to this
> ... love to see the Cypress support library exposed as an NPM package
Hopefully we can have it soon. Unfortunately, not high on my priority list. So, if anyone can pick up, that would be great.

All looks good to me! Can't wait to see how this play well with the Playbooks. Thanks for taking care 💯

**Review by agarciamontoro — APPROVED** [review]
This is neat :)

**Comment by agarciamontoro** [comment]
Not sure if we want to merge now or wait after 1.16?

**Comment by lieut-data** [comment]
Given it doesn't touch the core product (and still runs tests!), I'm going to merge.

**Pull request merged**
