### PR TITLE
MM-39126 Use natural lang for default update time

### PR DESCRIPTION
**Pull request by pascalhein**
#### Summary
When specifying the default update timer, we currently
have to use a modal with hour/minute/day for custom
duration. Instead, let's re-use the natural language
input from the status update modal. This supports
entering durations such as "2 minutes", "6 days",
"3 hours 5 seconds".

Replaces a lot of custom-written code with a call to
DateTimeInput.

image

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/18566
JIRA: https://mattermost.atlassian.net/browse/MM-39126

#### Checklist
- [ ] ~Telemetry updated~
- [ ] ~Gated by experimental feature flag~
- [ ] ~Unit tests updated~

### CODE REVIEW

**Comment by pascalhein** [comment]
Hi @abhijit-singh and @calebroseland, thanks for your feedback!

I've implemented your suggestions: removing 'Never' and the X-to-clear button. However, that means that once an option has been clicked or typed, there is no way to reset it to the initial empty state. Is that intended?

**Review by calebroseland — APPROVED** [review]
@pascalhein I think due to the `never` option being removed, and reminder timers being required now—the value should always be _something_. (I believe that is intended.)

**Review by abhijit-singh — APPROVED** [review]
Yep, that's intended. Thank you @pascalhein!

**Comment by lieut-data** [comment]
@calebroseland, I wasn't sure of the status of this PR -- heads up I just looped you back in for a review to make sure this gets merged or reworked as needed :)

**Pull request merged**
