### PR TITLE
MM-55175 Do not hide assigned user name

### PR DESCRIPTION
**Pull request by rajatdangat**
## Summary
Do not hide the assigned user's name when a due date or action is assigned to a task.

## Ticket Link
Fixes: https://github.com/mattermost/mattermost/issues/25218

Jira ticket: https://mattermost.atlassian.net/browse/MM-55175

## Screenshots
| Before                                                                                                                                                                   | After                                                                                                                                                                    |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Sidebar Expanded Screenshot from 2023-11-04 13-51-55  | Sidebar Expanded Screenshot from 2023-11-04 13-53-11  |
| Sidebar collapsed Screenshot from 2023-11-04 13-51-16 | Sidebar collapsed Screenshot from 2023-11-04 13-52-59 |
| Playbook Screenshot from 2023-11-04 13-57-35          | Playbook Screenshot from 2023-11-04 13-55-21          |

## Checklist
- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

### CODE REVIEW

**Review by calebroseland — CHANGES_REQUESTED** [review]
I agree with removing the withoutName part, but if we're just going to hardcode it false, maybe we should just remove the prop/internals altogether.

Also, there's an issue with overlapping now depending on other task properties and RHS' width: 

https://github.com/mattermost/mattermost-plugin-playbooks/assets/11724372/0a6e2838-44fd-4977-bf78-d6e23e13e2a6

CSS-wise, I'd suggest something like this:
[MM-55176-assigned-to-wrapping.patch](https://github.com/mattermost/mattermost-plugin-playbooks/files/13272461/MM-55176-assigned-to-wrapping.patch)

**Review by crspeller — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Comment by lindy65** [comment]
Hi @rajatdangat - I'm seeing an issue in the right-hand-side (RHS) whether it's expanded or collapsed.  If I add an assignee to a task, the full username is visible but as soon as I also add a due date, the username is truncated

image

image

image

I'm also seeing another issue where, if I tick off a task as done, the username becomes visible (if I uncheck the task again, the username truncates again)

image

cc @calebroseland @crspeller

**Comment by calebroseland** [comment]
@lindy65 @crspeller looks like the spinwick didn't pick up the build

CleanShot 2023-11-10 at 10 32 18@2x
(should have a hash appended, I think)
CleanShot 2023-11-10 at 10 30 37@2x

**Review by lindy65 — APPROVED** [review]
Thanks @calebroseland - I've tested this PR on your dev cloud server (thanks for helping with that) and it looks good to me 👍 
cc @rajatdangat @crspeller

**Pull request merged**
