### PR TITLE
MM-58173 fix overlapping UI and modals

### PR DESCRIPTION
**Pull request by matthewbirtch**
## Summary
Fixes an issue with the preview text overlapping dropdown items in the create playbook modal. Also fixes issues with playbooks modals spacing/layout.

## Ticket Link
Fixes: https://github.com/mattermost/mattermost/issues/27536
Fixes: https://github.com/mattermost/mattermost/issues/26269

Jira: https://mattermost.atlassian.net/browse/MM-58173
Jira: https://mattermost.atlassian.net/browse/MM-56861

## Before / After
| Before | After |
|---|---|
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |

### CODE REVIEW

**Review by asaadmahmood — APPROVED** [review]
LGTM

**Review by lieut-data — APPROVED** [review]

**Review by JulienTant — APPROVED** [review]

**Comment by matthewbirtch** [comment]
@lieut-data or @JulienTant could you help merge?

**Comment by lindy65** [comment]
Hey @matthewbirtch - I'm still seeing the old screens in the spinwick...  I've added an enterprise licence and playbooks 1.39.3 is installed...  Any ideas? Perhaps I need to update the branch and redeploy the spinwick?

**Comment by matthewbirtch** [comment]
> Hey @matthewbirtch - I'm still seeing the old screens in the spinwick... I've added an enterprise licence and playbooks 1.39.3 is installed... Any ideas? Perhaps I need to update the branch and redeploy the spinwick?

Hey @lindy65 I'm not sure. In your experience does spinwick use the right version of the playbooks plugin from playbooks PRs?

**Comment by JulienTant** [comment]
@lindy65 it appears that the spinwick is using the prepackaged version of the plugin, not the one from the current working branch :(

**Comment by lindy65** [comment]
Ah you are correct Julien!  I keep forgetting that :(  @matthewbirtch - I'll QA-defer this PR and test after merge

**Pull request merged**
