### PR TITLE
[MM-38575] Import luxon as external dependency from mattermost-webapp, bump min version

### PR DESCRIPTION
**Pull request by mathiasvr**
#### Summary

In playbooks, define/import luxon as external dependency provided from mattermost-webapp.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/18588

#### Checklist

- ~~[ ] Telemetry updated~~
- ~~[ ] Gated by experimental feature flag~~
- ~~[ ] Unit tests updated~~

### CODE REVIEW

**Comment by calebroseland** [comment]
Thanks for the PR, @mathiasvr! Sorry for the delay. I think due to the nature of the way this will remove `luxon` from the playbooks bundle, we're going to have to wait to merge this.

We'll respond back here once MM 6.1 (or whichever version https://github.com/mattermost/mattermost-webapp/pull/9107 ships in) propagates to http://community.mattermost.com, then we'll be safe to merge this.

We're also going to need to bump `min_server_version` (in `plugin.json`) before this gets merged.

**Comment by lieut-data** [comment]
@calebroseland, I think you mentioned this one is ready to be merged? Do we still need to bump the minimum server version?

**Comment by calebroseland** [comment]
> @calebroseland, I think you mentioned this one is ready to be merged? Do we still need to bump the minimum server version?

Yes, that'll need to be bumped.

@mathiasvr would you mind bumping `min_server_version` to `6.1`?

**Comment by mathiasvr** [comment]
@calebroseland Sure no problem ;)

**Review by calebroseland — APPROVED** [review]
Thanks, @mathiasvr!

**Comment by calebroseland** [comment]
🔥 `/thaw`

**Pull request merged**
